pub mod status_kind_ex {
    pub const FIGHTER_LINK_STATUS_KIND_LAST: i32 = 0x1E8;
    pub const FIGHTER_LINK_STATUS_KIND_FINISHING_BLOW: i32 = FIGHTER_LINK_STATUS_KIND_LAST+1;
    pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_N_CANCEL: i32 = FIGHTER_LINK_STATUS_KIND_LAST+2;
    pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_CANCEL: i32 = FIGHTER_LINK_STATUS_KIND_LAST+3;
    pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_FALL: i32 = FIGHTER_LINK_STATUS_KIND_LAST+4;
    pub const FIGHTER_LINK_STATUS_KIND_SPECIAL_HI_2: i32 = FIGHTER_LINK_STATUS_KIND_LAST+5;
    pub const FIGHTER_LINK_STATUS_KIND_SHIELD_SURF_START: i32 = FIGHTER_LINK_STATUS_KIND_LAST+6;
    pub const FIGHTER_LINK_STATUS_KIND_SHIELD_SURF_LOOP: i32 = FIGHTER_LINK_STATUS_KIND_LAST+7;
    pub const FIGHTER_LINK_STATUS_KIND_SHIELD_SURF_JUMP: i32 = FIGHTER_LINK_STATUS_KIND_LAST+8;
    pub const FIGHTER_LINK_STATUS_KIND_SHIELD_SURF_ATTACK: i32 = FIGHTER_LINK_STATUS_KIND_LAST+9;
    pub const FIGHTER_LINK_STATUS_KIND_SHIELD_SURF_END: i32 = FIGHTER_LINK_STATUS_KIND_LAST+10;
    pub const FIGHTER_LINK_STATUS_KIND_MORTAL_DRAW: i32 = FIGHTER_LINK_STATUS_KIND_LAST+11;
    pub const FIGHTER_LINK_STATUS_KIND_SKYWARD_CHARGE: i32 = FIGHTER_LINK_STATUS_KIND_LAST+12;
}
pub mod param {
    pub const LINK_FLOAT_FINISHING_BLOW_DAMAGE_MIN : f32 = 100.0;
    pub const LINK_INT_FINISHING_BLOW_KNOCKOUT_FRAME : i32 = 30;
    
    pub const LINK_FLOAT_ATTACK_S4_SPEED_X : f32 = 1.2;
    pub const LINK_FLOAT_ATTACK_S4_SPEED_Y : f32 = 1.7;
    pub const LINK_FLOAT_ATTACK_S4_BRAKE_X : f32 = 0.023;
    pub const LINK_FLOAT_ATTACK_S4_LIMIT_Y : f32 = -4.0;
    pub const LINK_FLOAT_ATTACK_S4_ACCEL_Y : f32 = -0.15;
    pub const LINK_FLOAT_ATTACK_S4_ACCEL_MUL : f32 = 2.0;

    pub const LINK_INT_SPECIAL_HI_RISE_FRAME : i32 = 14;
    pub const LINK_FLOAT_SPECIAL_HI_RISE_BRAKE_X : f32 = 0.05;
    pub const LINK_FLOAT_SPECIAL_HI_RISE_ACCEL_Y : f32 = 0.36;
    pub const LINK_FLOAT_SPECIAL_HI_RISE_STABLE_Y : f32 = 3.0;

    pub const LINK_INT_SPECIAL_HI_CANCEL_FORGIVENESS : i32 = 4;
    pub const LINK_INT_SPECIAL_HI_BOMBDROP_DISABLE : i32 = 14;
    pub const LINK_FLOAT_SPECIAL_HI_BOMBDROP_OFFSET_Y : f32 = -4.0;
    pub const LINK_INT_SPECIAL_HI_BOMBDROP_BLAST : i32 = 12;

    pub const LINK_INT_SPECIAL_HI_BRAKE_FRAME : i32 = 45;
    pub const LINK_FLOAT_SPECIAL_HI_FALL_STABLE_X : f32 = 1.0;
    pub const LINK_FLOAT_SPECIAL_HI_FALL_ACCEL_X : f32 = 0.009;
    pub const LINK_FLOAT_SPECIAL_HI_FALL_STABLE_Y : f32 = 0.3;
    pub const LINK_FLOAT_SPECIAL_HI_FALL_ACCEL_Y : f32 = -0.07;
    pub const LINK_FLOAT_SPECIAL_HI_FALL_BRAKE_Y : f32 = 1.0;

    pub const LINK_INT_SHIELD_SURF_FORGIVENESS:i32 = 2;

    pub const LINK_FLOAT_SHIELD_SURF_START_X:f32 = 1.5;
    pub const LINK_FLOAT_SHIELD_SURF_START_Y:f32 = 0.3;

    pub const LINK_FLOAT_SHIELD_SURF_LOOP_BRAKE_AIR:f32 = 0.009;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_SLOPE_MAX:f32 = 50.0;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_SPEED_STABLE_MAX:f32 = 3.5;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_ACCEL_MIN:f32 = 0.003;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_ACCEL_MAX:f32 = 0.03;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_BRAKE_GROUND_MIN:f32 = 0.009;
    pub const LINK_FLOAT_SHIELD_SURF_LOOP_BRAKE_GROUND_MAX:f32 = 0.06;
    pub const LINK_FLOAT_SHIELD_SURF_JUMP_Y:f32 = 1.3;
}
pub mod vars {
    pub mod instance {//0x01??
        //flag
        pub const LINK_FLAG_SPECIAL_HI_CANCEL_LANDING : i32 = 0x0100;
        pub const LINK_FLAG_SKYWARD_STRIKE_IS_CHARGED : i32 = 0x0101;
        //int
        pub const LINK_INT_SPECIAL_HI_BOMBDROP_DISABLE_FRAME : i32 = 0x0100;
        pub const LINK_INT_SKYWARD_STRIKE_EFFECT_HANDLE: i32 = 0x0101;
        // float
        // pub const LINK_FLOAT_ : i32 = 0x0100;
    }
    pub mod status {//0x11??
        //flag
        pub const LINK_FLAG_HAS_ITEM_ANIM : i32 = 0x1100;
        pub const LINK_FLAG_ATTACK_IS_BUFFERD : i32 = 0x1101;
        pub const LINK_FLAG_FINISHING_BLOW_THROW : i32 = 0x1102;
        pub const LINK_FLAG_ATTACK_S4_JUMP : i32 = 0x1103;
        pub const LINK_FLAG_SPECIAL_HI_END_RISE : i32 = 0x1104;
        pub const LINK_FLAG_SPECIAL_HI_END_ENABLE_CANCEL : i32 = 0x1105;
        pub const LINK_FLAG_SPECIAL_HI_2_BRAKE : i32 = 0x1106;
        pub const LINK_FLAG_APPEAL_ENABLE_MORTAL_DRAW : i32 = 0x1107;
        pub const LINK_FLAG_APPEAL_ENABLE_SKYWARD_CHARGE : i32 = 0x1108;
        pub const LINK_FLAG_SHIELD_SURF_HOP : i32 = 0x1109;
        //int
        pub const LINK_INT_SPECIAL_HI_END_RISE_COUNT : i32 = 0x1100;
        pub const LINK_INT_SPECIAL_HI_2_BRAKE_COUNT : i32 = 0x1101;
        //float
        pub const LINK_FLOAT_SHIELD_SURF_LOOP_SLOPE : i32 = 0x1100;
        pub const LINK_FLOAT_APPEAL_PREV_MOTION_FRAME : i32 = 0x1101;
    }
}